#!/bin/bash
#audacious2 -i gtkui -e "$@"
#if [ ${#*} -gt 0 ]; then for i in "$@"; do echo "$i"; done; else cat; fi| sed 's/^/add\ "/;s/$/"/'|nyxmms2
if [ ${#*} -gt 0 ]; then xmms2 add "$@"; else xargs -d\\n xmms2 add; fi
