#!/bin/bash -x
#audacious2 -i gtkui -e "$@"
#if [ ${#*} -gt 0 ]; then for i in "$@"; do echo "$i"; done; else cat; fi| sed 's/^/add\ "/;s/$/"/'|nyxmms2

export st="`xmms2 status`"
printenv st|grep ^Stop && {
  export pl="`xmms2 playlist list|sed 's/[* ]//g'`"
  x=0
  while printenv pl|grep ^pl$x$; do (( x++ )); done
  xmms2 playlist create pl$x
  xmms2 playlist switch pl$x
}

if [ ${#*} -gt 0 ]; then xmms2 add "$@"; else xargs -d\\n xmms2 add; fi

printenv st|grep -v ^Playing && xmms2 play
export -n st pl
