#!/usr/bin/perl

#use DBM::Deep;
#my $db = DBM::Deep->new(@ARGV[0]);
$/="\0";
dbmopen(%db, @ARGV[0], 0666);
while(<STDIN>)
{
#	chomp;
	my ($k, $v) = split(' ', $_, 2);
	$db{$k} = $db{$k}.$v;
	#print $k." -> ".$v."$/";
	#print $k." -> ".$db{$k}."$/";
}
dbmclose(%db);
