#!/usr/bin/perl

#use DBM::Deep;
#my $db = DBM::Deep->new(@ARGV[0]);
$/="\0";
dbmopen(%db, @ARGV[0], 0666);
while(<STDIN>)
{
	if (/(.*?)(?:(?<!:): (.*))/)
	{
		$k=$1;
		$k =~ s/::/:/g;
		$db{$k} = $db{$k}.$2;
	}
}
dbmclose(%db);
