#!/bin/bash -x
#audacious2 -i gtkui -e "$@"
#if [ ${#*} -gt 0 ]; then for i in "$@"; do echo "$i"; done; else cat; fi| sed 's/^/add\ "/;s/$/"/'|nyxmms2
if [ "$1" = "-" ]; then shift; else
st="`xm status|grep -o ^[^:]*`"
[ $st = "Stopped" ] && {
  export pl="`xm playlist list|sed 's/[* ]//g'`"
  x=0
  while printenv pl|grep ^pl$x$; do (( x++ )); done
  xm playlist create pl$x
  xm playlist switch pl$x
}
fi
#addr=$HOSTNAME
#addr=$(ifdata -pa $(ip -4 link show up|grep ^[0-9]|grep -v lo:|sort -nr|cut -d: -f2))
addr=$(ip -o -4 addr show up|grep -vw lo|sed s@\ \\+@/@g|cut -d/ -f4)
#if [ ${#*} -gt 0 ]; then realpath "$@"; else xargs -rd\\n realpath; fi|sed 's_^/media/_/home/tc/eee/_'|xargs -rd\\n xm add
(if [ ${#*} -gt 0 ]; then for i; do realpath "$i"; done; else xargs -rd\\n realpath; fi) |
	#sed "s_^/media/_/home/tc/sshfs/$USER@emileee/media/_"|
	sed '/^\/darkstar\/\|^\/green\/\|^\/mnt\//!s_^_/home/tc/sshfs/'"$USER@$addr/_"| sed '/^file:/!s@^@file://@'| tee /dev/stderr|
	xargs -rd\\n xm add
#if [ ${#*} -gt 0 ]; then realpath "$@"; else xargs -rd\\n realpath; fi|xargs -rd\\n xm add

[ "$st" != "Playing" ] && xm play
export -n st pl
