#!/bin/bash -x
#sh ~/bin/rmconv/ogg.sh $*

trap 'exit 1' SIGINT SIGTERM
for i; do
	mkdir -p "${DIR}`dirname \"$i\"`" &&
	mplayer -noconsolecontrols -vc null -vo null -ao pcm:fast "$i" |tee info &&
	oggenc -q 6 -o "${DIR}$i.ogg" audiodump.wav -t "`(sed -n 's/^ name: //p' info;basename \"$i\"|sed 's/\.r[am]m\?$//')|head -1`" -a "`(sed -n 's/^ author: //p' info;dirname \"$i\")|head -1`" &&
	rm audiodump.wav info && continue
	exit 1
done
