#!/bin/sh
if lsmod |grep -q rt2860sta && not gksudo rmmod rt2860sta; then 
zenity --info --text="Try disabling wireless first"
else
lsmod |grep -q rt3562sta && gksudo rmmod rt3562sta
gksudo modprobe rt3562sta
fi
o find /lib/modules/ -name 'rt2*.ko' -delete
