#!/bin/bash -x
source $HOME/bin/nax/autocurling
a="$1"
[ -z "$a" ] && a=1
grep FileException: cpl2tag$1.log -A 6|grep mp4$|grep -v /\\.mp4 |tee corrupt$1.log|while read i; do recooktrack "$i"; done #2>&1|tee cpl2tag$a.log

